# Generated by Django 5.2.1 on 2025-05-25 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("turismo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="touristspot",
            name="location",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-ZÀ-ú\\s]+\\,[A-Za-z]{2}$", 'Formato: "Cidade,País"'
                    )
                ],
            ),
        ),
    ]
