# Generated by Django 5.2.1 on 2025-05-26 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("turismo", "0002_alter_touristspot_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="touristspot",
            name="opening_hours",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{2}:\\d{2} às \\d{2}:\\d{2}$", "Formato: 08:00 às 18:00"
                    )
                ],
            ),
        ),
    ]
