# Generated by Django 5.2.1 on 2025-05-26 01:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("turismo", "0003_alter_touristspot_opening_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="touristspot",
            name="location",
            field=models.CharField(
                help_text='Digite no formato "Cidade, País" (Ex: Paris, França)',
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_location",
                        message='Formato requerido: "Cidade, País" (Ex: Natal, Brasil)',
                        regex="^[a-zA-ZÀ-ú\\s]+,\\s*[A-Za-z]{2,}$",
                    )
                ],
            ),
        ),
    ]
