# Generated by Django 5.2.1 on 2025-05-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("turismo", "0005_alter_touristspot_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Spot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="spots/")),
            ],
        ),
    ]
