# Generated by Django 5.2.1 on 2025-05-29 03:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("turismo", "0006_spot"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Spot",
        ),
    ]
